name: Deploy to IIS via Web Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore Packages
        run: nuget restore dotnet.sln

      - name: Build Solution
        run: msbuild.exe dotnet.sln /p:Configuration=Release

      - name: Publish
        run: msbuild.exe dotnet.sln /p:DeployOnBuild=true 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-deploy-package
          path: D:/a/dotnetcode2/dotnetcode2/obj/Debug/Package/dotnet.zip
          
      - name: Download Artifact to Laptop
        uses: actions/download-artifact@v4
        with:
         name: dotnet-deploy-package
         path: C:/web




