name: Deploy to IIS via Web Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore Packages
        run: nuget restore dotnet.sln

      - name: Build Solution
        run: msbuild.exe dotnet.sln /p:Configuration=Release

      - name: Publish
        run: msbuild.exe dotnet.sln /p:DeployOnBuild=true 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-deploy-package
          path: D:/a/dotnetcode2/dotnetcode2/obj/Debug/Package/dotnet.zip
          
      - name: Copy Artifact to Repo
        run: |
         mkdir -p $GITHUB_WORKSPACE/artifacts
         cp D:/a/dotnetcode2/dotnetcode2/obj/Debug/Package/dotnet.zip $GITHUB_WORKSPACE/artifacts/

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
         fetch-depth: 0  # This is essential for git push to work later


      - name: Commit and Push Artifact
        run: |
         cd $GITHUB_WORKSPACE
         git config --global user.email "kukatladevopsengineer@gmail.com"
         git config --global user.name "venkat"
         git add artifacts/dotnet.zip
         git commit -m "Uploaded artifact to repository"
         git push origin master  # or 'main' depending on your branch





