name: Deploy to IIS via File Copy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Allow PowerShell Scripts
        run: Set-ExecutionPolicy RemoteSigned -Scope Process -Force
        shell: powershell

      # Optional: Restore packages if needed
      # - name: Restore Packages
      #   run: nuget restore dotnet.sln

      - name: Build Solution
        run: msbuild.exe dotnet.sln /p:Configuration=Release

      - name: Create Output Folder
        run: mkdir -Force D:\a\dotnetcode2\output

      - name: Publish Project to Output Folder
        run: |
          msbuild.exe dotnet.sln `
            /p:DeployOnBuild=true `
            /p:WebPublishMethod=FileSystem `
            /p:PublishDir="D:\a\dotnetcode2\output\" `
            /p:Configuration=Release
      
      - name: List Published Files (Debug)
        run: dir D:\a\dotnetcode2\output

      - name: Publish via dotnet CLI
        run: dotnet publish path\to\dotnet.csproj -c Release -o D:\a\dotnetcode2\output


      - name: Upload Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-deploy-package
          path: D:/a/dotnetcode2/output
          if-no-files-found: error

      - name: Copy Files to IIS Site Folder
        run: |
          robocopy "D:\a\dotnetcode2\output" "C:\hello" /MIR
